apiVersion: v1
kind: Service
metadata:
  name: node-app-external
spec:
  type: LoadBalancer
  selector:
    app: node
  ports:
  - port: 80
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: node-app-internal
spec:
  selector:
    app: node
  ports:
  - port: 80
    targetPort: 8080
---
