apiVersion: v1
kind: Service
metadata:
  name: node-app-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: node
  ports:
  - port: 80
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: node-app-leader
spec:
  type: LoadBalancer
  selector:
    app: node
    id: "1"
  ports:
  - port: 80
    targetPort: 8080
---
